-- ============================================================
-- ★ 이 파일은 테스트 전용 사본이다. 정본은 Docs/Erd/A307_ddl_final.sql 이다. ★
--
-- 정본이 바뀌면 이 파일도 같은 커밋에서 함께 고친다. 손으로 유지되는 사본이라
-- 그러지 않으면 조용히 낡고, 그 순간 "테스트 통과"가 "기동 가능"을 보장하지 않게 된다.
-- 실제로 그 사고가 한 번 일어났다 — estimate_validation.llm_summary 가 여기서는 CLOB,
-- 정본에서는 TEXT 였고, 엔티티의 @Lob 이 H2 하고만 맞아 테스트는 전부 통과하는데
-- PostgreSQL bootRun 만 SchemaManagementException 으로 죽었다 (answer24 F-1).
--
-- 회귀 방어: SchemaConformityTest 가 이 파일과 정본을 컬럼·NULL·CHECK 단위로 대조한다.
-- 테스트를 통과시키려고 여기의 제약을 정본보다 약하게 만들지 않는다.
--
-- 컬럼명 · NULL 여부 · CHECK 제약은 원본과 같게 유지한다 (Entity 매핑 검증 목적).
--
-- 원본과 다른 점 (H2 미지원)
--   · 부분 인덱스 WHERE 절 → 전체 인덱스로 대체
--   · BIGSERIAL → GENERATED BY DEFAULT AS IDENTITY
--   · TIMESTAMPTZ → TIMESTAMP WITH TIME ZONE
--   · JSONB → JSON            (estimate_item.ref_condition — answer24 F-4)
--   · TEXT → VARCHAR         (estimate_validation.llm_summary — 타입군이 같다. answer24 F-1)
--   · pgvector VECTOR 타입을 쓰는 테이블은 아예 옮기지 않았다
--
-- 커버리지: 정본 42테이블 중 33테이블 (관리자 기능이 repair_code · repair_method_rule ·
-- estimate_validation_rule · audit_log 를 추가했고, prompt58 이 analysis_stage 를 옮겼으며,
-- S15P21A307-288 이 estimate_notice 를, S15P21A307-157 이 analysis_image_result 를 더했다.
-- S15P21A307-509 가 정비 체크리스트 3종(repair_checklist_common_item · repair_checklist ·
-- repair_checklist_item)을, S15P21A307-510 이 정비소 확인 질문 2종(repair_question ·
-- repair_question_item)을, S15P21A307-513 이 사고 데이터 검수(accident_review)를 양쪽에
-- 더했으며, S15P21A307-355 가 배치 실행 기록 2종(batch_job_execution ·
-- data_validation_error)을 엔티티와 함께 여기로 옮겼다. S15P21A307-232 가 정본에만 더한 3개
-- (feature_pipeline_version · repair_case_damage_feature · repair_case_image_part_annotation)는
-- 파이프라인 전용이라 여기 없다).
-- @Entity 가 붙은 테이블은 전부 여기에 있다.
-- 누락 9개 — 아직 엔티티도 소비자도 없는 도메인이다. SchemaConformityTest
-- .KNOWN_MISSING_TABLES 와 같은 목록이어야 한다.
--   embedding_model_version
--   repair_case, repair_case_item, repair_case_image, repair_case_roi_embedding
--   estimate_report
--   feature_pipeline_version, repair_case_damage_feature,
--   repair_case_image_part_annotation             (S15P21A307-232 에서 추가)
--
-- ⚠ repair_case 계열 4개가 없어 유사 사례 검색 종단 테스트를 H2 로 구성할 수 없다.
--   검색 조건을 만드는 경계(AccidentVehicleSearchConditionResolver)까지만 테스트되고,
--   그 조건으로 실제 사례가 조회되는지는 여기서 증명할 수 없다 (prompt23 5-3).
--   유사 사례 담당자가 착수할 때 이 4개를 함께 옮겨야 한다.
-- ============================================================

-- accident · analysis_job · member 를 참조하므로 그 셋보다 먼저 지운다.
DROP TABLE IF EXISTS data_validation_error;
DROP TABLE IF EXISTS batch_job_execution;
DROP TABLE IF EXISTS accident_review;
DROP TABLE IF EXISTS repair_question_item;
DROP TABLE IF EXISTS repair_question;
DROP TABLE IF EXISTS repair_checklist_item;
DROP TABLE IF EXISTS repair_checklist;
DROP TABLE IF EXISTS repair_checklist_common_item;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS repair_method_rule;
DROP TABLE IF EXISTS repair_code;
DROP TABLE IF EXISTS estimate_validation_question;
DROP TABLE IF EXISTS estimate_validation_report;
DROP TABLE IF EXISTS estimate_validation_item;
DROP TABLE IF EXISTS estimate_validation;
DROP TABLE IF EXISTS estimate_validation_rule;
DROP TABLE IF EXISTS estimate_notice;
DROP TABLE IF EXISTS estimate_item;
DROP TABLE IF EXISTS estimate;
DROP TABLE IF EXISTS damaged_part;
DROP TABLE IF EXISTS analysis_image_result;
DROP TABLE IF EXISTS analysis_stage;
DROP TABLE IF EXISTS analysis_job;
DROP TABLE IF EXISTS repair_cost_stat;
DROP TABLE IF EXISTS part_name_mapping;
DROP TABLE IF EXISTS part_code;
DROP TABLE IF EXISTS accident_image_asset;
DROP TABLE IF EXISTS accident_image;
DROP TABLE IF EXISTS accident;
DROP TABLE IF EXISTS vehicle;
DROP TABLE IF EXISTS vehicle_model;
DROP TABLE IF EXISTS terms_agreement;
DROP TABLE IF EXISTS member;

CREATE TABLE member (
    member_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider          VARCHAR(20)  NOT NULL,
    provider_user_id  VARCHAR(255) NOT NULL,
    nickname          VARCHAR(12)  NOT NULL,
    email             VARCHAR(255),
    profile_image_key VARCHAR(500),
    role              VARCHAR(20)  NOT NULL DEFAULT 'USER',
    status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    withdrawn_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_member_provider UNIQUE (provider, provider_user_id),
    CONSTRAINT ck_member_provider CHECK (provider IN ('KAKAO','GOOGLE')),
    CONSTRAINT ck_member_role     CHECK (role IN ('USER','ADMIN')),
    CONSTRAINT ck_member_status   CHECK (status IN ('ACTIVE','WITHDRAWN'))
);

CREATE TABLE terms_agreement (
    agreement_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT      NOT NULL REFERENCES member(member_id) ON DELETE RESTRICT,
    terms_type   VARCHAR(20) NOT NULL,
    version      VARCHAR(20) NOT NULL,
    agreed_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_terms_type CHECK (terms_type IN ('SERVICE','PRIVACY'))
);

CREATE TABLE vehicle_model (
    model_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer VARCHAR(50)  NOT NULL,
    model_name   VARCHAR(100) NOT NULL,
    vehicle_type VARCHAR(20)  NOT NULL,
    car_class    VARCHAR(20)  NOT NULL,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    -- 관리자 동시 수정의 lost update 방지. JPA @Version 이 UPDATE 조건에 넣는다.
    version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_vm UNIQUE (manufacturer, model_name),
    CONSTRAINT ck_vm_type  CHECK (vehicle_type IN ('SEDAN','SUV','VAN','TRUCK')),
    CONSTRAINT ck_vm_class CHECK (car_class IN ('CityCar','Compact','Mid-size','Full-size'))
);

CREATE TABLE vehicle (
    vehicle_id BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT   NOT NULL REFERENCES member(member_id)       ON DELETE RESTRICT,
    model_id   BIGINT   NOT NULL REFERENCES vehicle_model(model_id) ON DELETE RESTRICT,
    model_year SMALLINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_v_year CHECK (model_year BETWEEN 1980 AND 2100)
);

CREATE INDEX ix_vehicle_member ON vehicle (member_id);

-- 삭제 테스트용. vehicle 을 ON DELETE RESTRICT 로 참조하는 유일한 테이블이다.
CREATE TABLE accident (
    accident_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id              BIGINT NOT NULL REFERENCES vehicle(vehicle_id) ON DELETE RESTRICT,
    vehicle_input_type      VARCHAR(10)  NOT NULL,
    snapshot_model_id       BIGINT       NOT NULL,
    snapshot_manufacturer   VARCHAR(50)  NOT NULL,
    snapshot_model_name     VARCHAR(100) NOT NULL,
    snapshot_vehicle_type   VARCHAR(20)  NOT NULL,
    snapshot_car_class      VARCHAR(20)  NOT NULL,
    snapshot_model_year     SMALLINT     NOT NULL,
    actual_repair_cost      INTEGER,
    actual_repair_completed_date DATE,
    repair_shop_name        VARCHAR(100),
    actual_cost_recorded_at TIMESTAMP WITH TIME ZONE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_ac_input_type CHECK (vehicle_input_type IN ('REGISTERED','DIRECT')),
    CONSTRAINT ck_ac_vehicle_type CHECK (snapshot_vehicle_type IN ('SEDAN','SUV','VAN','TRUCK')),
    CONSTRAINT ck_ac_car_class CHECK (snapshot_car_class IN ('CityCar','Compact','Mid-size','Full-size')),
    CONSTRAINT ck_ac_model_year CHECK (snapshot_model_year BETWEEN 1980 AND 2100),
    CONSTRAINT ck_ac_cost CHECK (actual_repair_cost IS NULL OR actual_repair_cost > 0)
);

-- 사고 이미지. 경로·크기 메타는 이 테이블이 아니라 accident_image_asset 에 있다.
-- 정본(A307_ddl_final.sql)과 컬럼·NULL 여부·CHECK·FK·인덱스를 항목별로 대조해 옮겼다.
CREATE TABLE accident_image (
    image_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accident_id       BIGINT       NOT NULL REFERENCES accident(accident_id) ON DELETE CASCADE,
    original_filename VARCHAR(255) NOT NULL,
    angle_code        VARCHAR(20),
    quality_status    VARCHAR(20)  NOT NULL DEFAULT 'PASS',
    quality_reason    VARCHAR(100),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_ai_quality CHECK (quality_status IN ('PASS','WARN'))
);

-- 원본·리사이즈·썸네일·블러를 행으로. variant 는 이미지당 1개(uk_aia).
-- OVERLAY 를 넣지 않는 것이 정본의 결정이다 — (job × image)마다 생겨 uk_aia 를 위반한다.
CREATE TABLE accident_image_asset (
    asset_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id   BIGINT       NOT NULL REFERENCES accident_image(image_id) ON DELETE CASCADE,
    variant    VARCHAR(20)  NOT NULL,
    s3_key     VARCHAR(500) NOT NULL,
    width      SMALLINT,
    height     SMALLINT,
    file_size  INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_aia      UNIQUE (image_id, variant),
    CONSTRAINT ck_aia_var  CHECK (variant IN ('ORIGINAL','RESIZED','THUMBNAIL','BLURRED')),
    CONSTRAINT ck_aia_size CHECK (file_size IS NULL OR file_size <= 20971520)
);

CREATE INDEX ix_img_accident ON accident_image (accident_id);

CREATE TABLE part_code (
    part_code     VARCHAR(50) PRIMARY KEY,
    name_ko       VARCHAR(50) NOT NULL,
    layout_zone   VARCHAR(20) NOT NULL,
    display_order SMALLINT NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    -- AI 핵심 라벨 32종과 견적 전용 확장 코드를 가르는 명시적 속성.
    -- 예전에는 display_order(1~32 vs 101~) 로만 구분됐는데 그것은 표시 순서일 뿐이라
    -- 관리자가 순서를 바꾸면 구분이 조용히 무너졌다.
    code_scope    VARCHAR(20) NOT NULL DEFAULT 'EXTENDED',
    version       BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_pc_zone  CHECK (layout_zone IN ('FRONT','REAR','SIDE_L','SIDE_R','TOP','UNDER')),
    CONSTRAINT ck_pc_scope CHECK (code_scope  IN ('AI_LABEL','EXTENDED'))
);

CREATE TABLE part_name_mapping (
    raw_name  VARCHAR(200) PRIMARY KEY,
    part_code VARCHAR(50) NOT NULL REFERENCES part_code(part_code) ON DELETE RESTRICT
);

CREATE TABLE analysis_job (
    job_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accident_id    BIGINT NOT NULL REFERENCES accident(accident_id) ON DELETE CASCADE,
    status         VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    retry_count    SMALLINT NOT NULL DEFAULT 0,
    failure_reason VARCHAR(50),
    model_version  VARCHAR(50),
    request_id     VARCHAR(64),
    pipeline_version_id BIGINT,
    started_at     TIMESTAMP WITH TIME ZONE,
    finished_at    TIMESTAMP WITH TIME ZONE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_aj_status CHECK (status IN ('QUEUED','PROCESSING','COMPLETED','FAILED')),
    CONSTRAINT ck_aj_retry CHECK (retry_count BETWEEN 0 AND 3)
);

-- 화면의 4단계 체크리스트. 단계가 늘어도 스키마 불변
CREATE TABLE analysis_stage (
    stage_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      BIGINT NOT NULL REFERENCES analysis_job(job_id) ON DELETE CASCADE,
    stage       VARCHAR(20) NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    detail      VARCHAR(100),
    started_at  TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_as UNIQUE (job_id, stage),
    CONSTRAINT ck_as_stage CHECK (stage IN ('PREPROCESS','DETECT','MATCH','ESTIMATE')),
    CONSTRAINT ck_as_status CHECK (status IN ('PENDING','RUNNING','DONE','FAILED'))
);

-- 분석 결과의 이미지 단위 기록. detections 는 정본 JSONB → H2 JSON (S15P21A307-157).
CREATE TABLE analysis_image_result (
    result_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id           BIGINT NOT NULL REFERENCES analysis_job(job_id) ON DELETE CASCADE,
    image_id         BIGINT NOT NULL REFERENCES accident_image(image_id) ON DELETE CASCADE,
    s3_key_overlay   VARCHAR(500),
    detections       JSON,
    is_excluded      BOOLEAN NOT NULL DEFAULT FALSE,
    exclusion_reason VARCHAR(50),
    CONSTRAINT uk_air UNIQUE (job_id, image_id),
    CONSTRAINT ck_air_reason CHECK (exclusion_reason IS NULL
                              OR exclusion_reason IN ('NOT_VEHICLE','RATIO_BELOW_THRESHOLD'))
);

CREATE TABLE damaged_part (
    damaged_part_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          BIGINT NOT NULL REFERENCES analysis_job(job_id) ON DELETE CASCADE,
    part_code       VARCHAR(50) NOT NULL REFERENCES part_code(part_code) ON DELETE RESTRICT,
    damage_type     VARCHAR(20) NOT NULL,
    repair_method   VARCHAR(20),
    severity_score  NUMERIC(6,2),
    confidence      NUMERIC(5,4) NOT NULL,
    CONSTRAINT uk_dp UNIQUE (job_id, part_code),
    CONSTRAINT ck_dp_damage CHECK (damage_type IN ('Scratched','Separated','Crushed','Breakage')),
    CONSTRAINT ck_dp_method CHECK (repair_method IN ('coating','sheet_metal','exchange','repair'))
);

CREATE TABLE estimate (
    estimate_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id               BIGINT NOT NULL REFERENCES analysis_job(job_id) ON DELETE CASCADE,
    version              SMALLINT NOT NULL DEFAULT 1,
    is_estimable         BOOLEAN NOT NULL DEFAULT TRUE,
    non_estimable_reason VARCHAR(100),
    labor_rate           INTEGER,
    total_hq             NUMERIC(7,2),
    total_min            INTEGER,
    total_median         INTEGER,
    total_max            INTEGER,
    ref_case_total       INTEGER,
    confidence_grade     VARCHAR(10),
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_est UNIQUE (job_id, version),
    CONSTRAINT ck_est_grade CHECK (confidence_grade IS NULL
                             OR confidence_grade IN ('HIGH','MEDIUM','LOW'))
);

CREATE TABLE estimate_item (
    estimate_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id       BIGINT NOT NULL REFERENCES estimate(estimate_id) ON DELETE CASCADE,
    damaged_part_id   BIGINT NOT NULL REFERENCES damaged_part(damaged_part_id) ON DELETE CASCADE,
    repair_method     VARCHAR(20) NOT NULL,
    standard_hq       NUMERIC(6,2),
    part_cost_median  INTEGER,
    labor_cost_median INTEGER,
    paint_material_cost INTEGER,
    item_min          INTEGER NOT NULL,
    item_median       INTEGER NOT NULL,
    item_max          INTEGER NOT NULL,
    ref_case_count    INTEGER NOT NULL,
    ref_condition     JSON NOT NULL,
    is_low_confidence BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_ei_method CHECK (repair_method IN ('coating','sheet_metal','exchange','repair'))
);

-- 고지 문구 (S15P21A307-288). 정본과 달리 TIMESTAMPTZ → TIMESTAMP WITH TIME ZONE.
CREATE TABLE estimate_notice (
    code          VARCHAR(30)  PRIMARY KEY,
    message       VARCHAR(500) NOT NULL,
    display_order SMALLINT     NOT NULL DEFAULT 0,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE repair_cost_stat (
    stat_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_class         VARCHAR(20) NOT NULL,
    part_code         VARCHAR(50) NOT NULL,
    damage_type       VARCHAR(20) NOT NULL,
    repair_method     VARCHAR(20) NOT NULL,
    source            VARCHAR(20) NOT NULL,
    case_count        INTEGER NOT NULL,
    hq_median         NUMERIC(6,2),
    cost_min          INTEGER NOT NULL,
    cost_p25          INTEGER NOT NULL,
    cost_median       INTEGER NOT NULL,
    cost_p75          INTEGER NOT NULL,
    cost_max          INTEGER NOT NULL,
    part_cost_median  INTEGER,
    labor_cost_median INTEGER,
    aggregated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_rcs UNIQUE (car_class, part_code, damage_type, repair_method, source)
);

-- ─── 관리자 마스터 표시층 · 판정 규칙 ────────────────────────────────────
-- canonical code 는 Java enum·DDL CHECK·통계 쿼리가 공유한다. 관리자가 새 코드를
-- 추가하면 DB 행만 늘고 계산이 실패하므로, 코드는 불변이고 표시명·순서·활성만 관리한다.
CREATE TABLE repair_code (
    code_type     VARCHAR(20) NOT NULL,
    code          VARCHAR(20) NOT NULL,
    display_name  VARCHAR(50) NOT NULL,
    display_order SMALLINT    NOT NULL DEFAULT 0,
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    version       BIGINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (code_type, code),
    CONSTRAINT ck_rcode_type CHECK (code_type IN ('REPAIR_METHOD','DAMAGE_TYPE'))
);

-- 심각도 구간 → 수리 방식. severity_score 의 값 범위는 아직 확정되지 않아
-- DB 는 "하한 < 상한" 만 강제한다. 경계는 [min, max) 이고 max_inclusive 로 마지막 구간만 닫는다.
CREATE TABLE repair_method_rule (
    rule_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    damage_type   VARCHAR(20)  NOT NULL,
    part_code     VARCHAR(50)  REFERENCES part_code(part_code) ON DELETE RESTRICT,
    severity_min  NUMERIC(6,2) NOT NULL,
    severity_max  NUMERIC(6,2) NOT NULL,
    max_inclusive BOOLEAN      NOT NULL DEFAULT FALSE,
    repair_method VARCHAR(20)  NOT NULL,
    priority      SMALLINT     NOT NULL DEFAULT 0,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_rmr_range  CHECK (severity_min < severity_max),
    CONSTRAINT ck_rmr_damage CHECK (damage_type   IN ('Scratched','Separated','Crushed','Breakage')),
    CONSTRAINT ck_rmr_method CHECK (repair_method IN ('coating','sheet_metal','exchange','repair'))
);

-- 이상 탐지 임계값. 행은 불변이고 현재 규칙은 rule_version 이 가장 큰 행이다 —
-- 활성 플래그를 두지 않아 "활성이 둘" 상태가 생기지 않는다.
CREATE TABLE estimate_validation_rule (
    rule_version                        INTEGER      PRIMARY KEY,
    reference_percentile                SMALLINT     NOT NULL,
    severe_over_p75_multiplier          NUMERIC(5,2) NOT NULL,
    caution_total_difference_ratio      NUMERIC(5,4) NOT NULL,
    needs_review_total_difference_ratio NUMERIC(5,4) NOT NULL,
    needs_review_item_count             SMALLINT     NOT NULL,
    changed_by                          BIGINT       REFERENCES member(member_id) ON DELETE SET NULL,
    change_note                         VARCHAR(200),
    created_at                          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_evr_version CHECK (rule_version >= 1),
    CONSTRAINT ck_evr_pct     CHECK (reference_percentile BETWEEN 1 AND 100),
    CONSTRAINT ck_evr_mult    CHECK (severe_over_p75_multiplier > 1.0),
    CONSTRAINT ck_evr_caution CHECK (caution_total_difference_ratio >= 0),
    CONSTRAINT ck_evr_review  CHECK (needs_review_total_difference_ratio >= caution_total_difference_ratio),
    CONSTRAINT ck_evr_count   CHECK (needs_review_item_count >= 1)
);

-- 관리자 변경 이력. 정본과 같은 정의다.
-- before_data·after_data 는 정본이 TEXT 이고 H2 는 길이 없는 VARCHAR 로 받는다 —
-- estimate_validation.llm_summary 와 같은 대응이다(answer24 F-1).
CREATE TABLE audit_log (
    audit_log_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_member_id BIGINT       REFERENCES member(member_id) ON DELETE SET NULL,
    action_type     VARCHAR(50)  NOT NULL,
    target_type     VARCHAR(50)  NOT NULL,
    target_id       VARCHAR(100) NOT NULL,
    request_id      VARCHAR(64),
    before_data     VARCHAR,
    after_data      VARCHAR,
    change_reason   VARCHAR(500),
    ip_address      VARCHAR(45),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX ix_audit_actor   ON audit_log (actor_member_id, created_at DESC);
CREATE INDEX ix_audit_target  ON audit_log (target_type, target_id, created_at DESC);
CREATE INDEX ix_audit_created ON audit_log (created_at DESC);
CREATE INDEX ix_audit_action  ON audit_log (action_type, created_at DESC);
CREATE INDEX ix_rmr_lookup    ON repair_method_rule (damage_type, is_active, priority);

-- 기준 데이터. 정본 쪽은 Docs/Erd/A307_admin_code_seed.sql 이 같은 값을 넣는다.
-- canonical code 는 추가되지 않으므로 여기 8행이 전부다.
INSERT INTO repair_code (code_type, code, display_name, display_order, is_active) VALUES
    ('REPAIR_METHOD','exchange',   '교환',     1, TRUE),
    ('REPAIR_METHOD','sheet_metal','판금',     2, TRUE),
    ('REPAIR_METHOD','coating',    '도장',     3, TRUE),
    ('REPAIR_METHOD','repair',     '수리',     4, TRUE),
    ('DAMAGE_TYPE',  'Scratched',  '스크래치', 1, TRUE),
    ('DAMAGE_TYPE',  'Separated',  '이격',     2, TRUE),
    ('DAMAGE_TYPE',  'Crushed',    '찌그러짐', 3, TRUE),
    ('DAMAGE_TYPE',  'Breakage',   '파손',     4, TRUE);

-- 이상 탐지 규칙 버전 1 = application.properties 배포 기본값. 값이 바뀌는 것이 아니라 옮겨 온 것이다.
INSERT INTO estimate_validation_rule (
    rule_version, reference_percentile, severe_over_p75_multiplier,
    caution_total_difference_ratio, needs_review_total_difference_ratio,
    needs_review_item_count, changed_by, change_note)
VALUES (1, 75, 1.50, 0.1000, 0.2000, 3, NULL, 'application.properties 배포 기본값 이관');

-- 고지 문구 (S15P21A307-288). 정본 쪽은 Docs/Erd/migrations/2026-09-14-estimate-notice.sql
-- 이 같은 값을 넣는다. 문구는 EstimateValidationService.LEGAL_NOTICE 상수와 글자까지 같아야
-- 하며, EstimateNoticeSeedConformityTest 가 그것을 고정한다.
INSERT INTO estimate_notice (code, message, display_order, is_active) VALUES
    ('LEGAL_NOTICE',
     '이 결과는 AI와 사례 통계를 이용한 참고용 추정치이며 실제 수리비와 다를 수 있고 특정 사업자를 평가하지 않습니다.',
     1, TRUE);

CREATE TABLE estimate_validation (
    validation_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id        BIGINT NOT NULL REFERENCES member(member_id) ON DELETE RESTRICT,
    accident_id      BIGINT NOT NULL REFERENCES accident(accident_id) ON DELETE CASCADE,
    estimate_id      BIGINT REFERENCES estimate(estimate_id) ON DELETE SET NULL,
    s3_key_file      VARCHAR(500),
    file_type        VARCHAR(10) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    claimed_total    INTEGER,
    llm_model        VARCHAR(50),
    llm_grade        VARCHAR(20),
    -- 정본은 TEXT. 엔티티에서 @Lob 을 제거해 VARCHAR 계열로 맞췄다 (answer24 F-1).
    -- CLOB 으로 되돌리면 H2 는 통과하고 PostgreSQL 기동만 실패하는 상태로 돌아간다.
    llm_summary      VARCHAR,
    failure_reason   VARCHAR(200),
    -- 이 검증이 어떤 이상 탐지 규칙 버전으로 판정됐는지. 규칙이 바뀌어도 과거 결과는
    -- 다시 계산되지 않으므로, 근거를 되짚으려면 버전이 남아야 한다.
    -- 컬럼 생성 이전 검증은 알 수 없어 NULL 이다.
    rule_version      INTEGER   REFERENCES estimate_validation_rule(rule_version) ON DELETE SET NULL,
    review_item_count INTEGER NOT NULL DEFAULT 0,
    total_item_count INTEGER NOT NULL DEFAULT 0,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    completed_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_ev_status CHECK (status IN ('QUEUED','PROCESSING','COMPLETED','FAILED')),
    CONSTRAINT ck_ev_type CHECK (file_type IN ('IMAGE','PDF','MANUAL')),
    CONSTRAINT ck_ev_grade CHECK (llm_grade IS NULL OR llm_grade IN ('APPROPRIATE','CAUTION','NEEDS_REVIEW')),
    CONSTRAINT ck_ev_file CHECK ((file_type = 'MANUAL' AND s3_key_file IS NULL)
                              OR (file_type <> 'MANUAL' AND s3_key_file IS NOT NULL)),
    CONSTRAINT ck_ev_done CHECK (completed_at IS NULL OR status IN ('COMPLETED','FAILED'))
);

CREATE TABLE estimate_validation_item (
    validation_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    validation_id      BIGINT NOT NULL REFERENCES estimate_validation(validation_id) ON DELETE CASCADE,
    line_no            SMALLINT NOT NULL,
    raw_item_name      VARCHAR(200) NOT NULL,
    normalized_item_name VARCHAR(100),
    part_code          VARCHAR(50) REFERENCES part_code(part_code) ON DELETE SET NULL,
    work_type          VARCHAR(20),
    quantity           SMALLINT NOT NULL DEFAULT 1,
    part_cost          INTEGER,
    labor_cost         INTEGER,
    subtotal           INTEGER,
    llm_flag           VARCHAR(30),
    llm_reason         VARCHAR(300),
    reference_min      INTEGER,
    reference_median   INTEGER,
    reference_p75      INTEGER,
    reference_max      INTEGER,
    reference_case_count INTEGER,
    CONSTRAINT uk_evi UNIQUE (validation_id, line_no)
);

CREATE TABLE estimate_validation_report (
    validation_id  BIGINT PRIMARY KEY REFERENCES estimate_validation(validation_id) ON DELETE CASCADE,
    status         VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    s3_key_pdf     VARCHAR(500),
    failure_reason VARCHAR(200),
    retry_count    SMALLINT NOT NULL DEFAULT 0,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    completed_at   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_evr_status CHECK (status IN ('QUEUED','PROCESSING','COMPLETED','FAILED')),
    CONSTRAINT ck_evr_retry CHECK (retry_count BETWEEN 0 AND 3),
    CONSTRAINT ck_evr_done CHECK (completed_at IS NULL OR status IN ('COMPLETED','FAILED'))
);

CREATE TABLE estimate_validation_question (
    question_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    validation_id      BIGINT NOT NULL REFERENCES estimate_validation(validation_id) ON DELETE CASCADE,
    validation_item_id BIGINT REFERENCES estimate_validation_item(validation_item_id) ON DELETE CASCADE,
    source_flag        VARCHAR(30) NOT NULL,
    display_order      SMALLINT NOT NULL,
    question_text      VARCHAR(500) NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_evq_item_flag UNIQUE (validation_item_id, source_flag),
    CONSTRAINT uk_evq_order UNIQUE (validation_id, display_order)
);

CREATE INDEX ix_ev_member ON estimate_validation(member_id, created_at DESC);
CREATE INDEX ix_ev_accident ON estimate_validation(accident_id, created_at DESC);

-- ═══ 정비 체크리스트 (S15P21A307-509) ═══════════════════════════════════════
-- 정본과 다른 점: BIGSERIAL → GENERATED BY DEFAULT AS IDENTITY,
--                TIMESTAMPTZ → TIMESTAMP WITH TIME ZONE. 그 밖은 글자까지 같다.
-- 사고 현장 체크리스트(checklist.json)와 다른 기능이다 — 이름이 겹쳐 repair_ 접두어로 갈랐다.

CREATE TABLE repair_checklist_common_item (
    code          VARCHAR(30)  PRIMARY KEY,
    message       VARCHAR(500) NOT NULL,
    display_order SMALLINT     NOT NULL DEFAULT 0,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- 공통 확인 항목 6종. 문안은 S15P21A307-462 본문에 확정된 것이고 여기서 다듬지 않는다.
-- 정본 쪽은 Docs/Erd/migrations/2026-09-14-repair-checklist.sql 이 같은 값을 넣는다.
INSERT INTO repair_checklist_common_item (code, message, display_order, is_active) VALUES
    ('ESTIMATE_DOCUMENT', '견적서 서면 수령·항목별 금액 확인',              1, TRUE),
    ('PART_GRADE',        '부품 등급(순정/OEM/재생/중고)과 부품 번호 확인', 2, TRUE),
    ('WORK_PHOTO',        '작업 전·후 사진 요청',                          3, TRUE),
    ('REPLACED_PART',     '교체된 부품 실물 확인',                         4, TRUE),
    ('WARRANTY',          '보증 기간·보증서 발급',                         5, TRUE),
    ('DURATION_LOANER',   '예상 소요 기간과 대차 여부',                    6, TRUE);

CREATE TABLE repair_checklist (
    checklist_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accident_id    BIGINT      NOT NULL REFERENCES accident(accident_id) ON DELETE CASCADE,
    status         VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    generation_no  SMALLINT    NOT NULL DEFAULT 1,
    failure_reason VARCHAR(200),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    completed_at   TIMESTAMP WITH TIME ZONE,
    regenerated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_rcl_accident   UNIQUE (accident_id),
    CONSTRAINT ck_rcl_status     CHECK (status IN ('QUEUED','PROCESSING','COMPLETED','FAILED')),
    CONSTRAINT ck_rcl_done       CHECK (completed_at IS NULL OR status IN ('COMPLETED','FAILED')),
    CONSTRAINT ck_rcl_generation CHECK (generation_no >= 1),
    CONSTRAINT ck_rcl_regen      CHECK (regenerated_at IS NULL OR generation_no > 1)
);

CREATE TABLE repair_checklist_item (
    item_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id  BIGINT       NOT NULL REFERENCES repair_checklist(checklist_id) ON DELETE CASCADE,
    source        VARCHAR(20)  NOT NULL,
    common_code   VARCHAR(30)  REFERENCES repair_checklist_common_item(code) ON DELETE RESTRICT,
    content       VARCHAR(500) NOT NULL,
    is_checked    BOOLEAN      NOT NULL DEFAULT FALSE,
    memo          VARCHAR(500),
    display_order SMALLINT     NOT NULL DEFAULT 0,
    checked_at    TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_rcli_common  UNIQUE (checklist_id, common_code),
    CONSTRAINT ck_rcli_source  CHECK (source IN ('AI','COMMON','USER')),
    CONSTRAINT ck_rcli_link    CHECK ((source =  'COMMON' AND common_code IS NOT NULL)
                                   OR (source <> 'COMMON' AND common_code IS NULL)),
    CONSTRAINT ck_rcli_checked CHECK (checked_at IS NULL OR is_checked = TRUE)
);

CREATE INDEX ix_rcli_checklist ON repair_checklist_item (checklist_id, display_order);

-- ═══ 정비소 확인 질문 (S15P21A307-510) ═══════════════════════════════════════
-- 정본과 다른 점: BIGSERIAL → GENERATED BY DEFAULT AS IDENTITY,
--                TIMESTAMPTZ → TIMESTAMP WITH TIME ZONE. 그 밖은 글자까지 같다.
-- 시드가 없다 — 질문에는 공통 문안 마스터가 없고 생성은 LLM 이 한다.
-- 구조는 위 정비 체크리스트와 같고, 다른 점(source 어휘 · 근거 컬럼)의 이유는 정본 12-2 절에 있다.

CREATE TABLE repair_question (
    question_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accident_id    BIGINT      NOT NULL REFERENCES accident(accident_id) ON DELETE CASCADE,
    status         VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    generation_no  SMALLINT    NOT NULL DEFAULT 1,
    failure_reason VARCHAR(200),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    completed_at   TIMESTAMP WITH TIME ZONE,
    regenerated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_rq_accident   UNIQUE (accident_id),
    CONSTRAINT ck_rq_status     CHECK (status IN ('QUEUED','PROCESSING','COMPLETED','FAILED')),
    CONSTRAINT ck_rq_done       CHECK (completed_at IS NULL OR status IN ('COMPLETED','FAILED')),
    CONSTRAINT ck_rq_generation CHECK (generation_no >= 1),
    CONSTRAINT ck_rq_regen      CHECK (regenerated_at IS NULL OR generation_no > 1)
);

CREATE TABLE repair_question_item (
    item_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id   BIGINT       NOT NULL REFERENCES repair_question(question_id) ON DELETE CASCADE,
    source        VARCHAR(20)  NOT NULL,
    content       VARCHAR(500) NOT NULL,
    part_code     VARCHAR(50)  REFERENCES part_code(part_code) ON DELETE RESTRICT,
    snapshot_part_name VARCHAR(50),
    damage_type   VARCHAR(20),
    repair_method VARCHAR(20),
    display_order SMALLINT     NOT NULL DEFAULT 0,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_rqi_source CHECK (source IN ('AI','USER')),
    CONSTRAINT ck_rqi_damage CHECK (damage_type   IN ('Scratched','Separated','Crushed','Breakage')),
    CONSTRAINT ck_rqi_method CHECK (repair_method IN ('coating','sheet_metal','exchange','repair')),
    CONSTRAINT ck_rqi_basis  CHECK ((part_code IS NULL) = (snapshot_part_name IS NULL)),
    CONSTRAINT ck_rqi_part   CHECK (part_code IS NOT NULL
                                 OR (damage_type IS NULL AND repair_method IS NULL))
);

CREATE INDEX ix_rqi_question ON repair_question_item (question_id, display_order);

-- ═══ 사고 데이터·피드백 검수 (S15P21A307-513) ═══════════════════════════════
-- 정본과 다른 점: BIGSERIAL → GENERATED BY DEFAULT AS IDENTITY,
--                TIMESTAMPTZ → TIMESTAMP WITH TIME ZONE,
--                부분 인덱스 WHERE 절 → 전체 인덱스. 그 밖은 글자까지 같다.
-- 아직 엔티티는 없다. -350 이 곧 붙이므로 처음부터 여기 둔다 — 나중에 옮기면 그 사이에
-- KNOWN_MISSING_TABLES 를 거쳐야 하고, 거기 들어간 테이블은 엔티티가 생기는 순간 기동 실패로만
-- 드러난다(S15P21A307-509 · -510 과 같은 판단).

-- ─── 배치 실행 기록 (S15P21A307-355) ───────────────────────────────────────
-- 파이프라인이 쓰고 백엔드가 읽는다. BatchJobExecution 엔티티가 생겨 여기로 옮겼다.
CREATE TABLE batch_job_execution (
    batch_job_execution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name               VARCHAR(100) NOT NULL,
    job_version            VARCHAR(100),
    status                 VARCHAR(20)  NOT NULL DEFAULT 'RUNNING',
    input_ref              VARCHAR(500),
    started_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    completed_at           TIMESTAMP WITH TIME ZONE,
    summary                JSON,
    error_message          VARCHAR,
    CONSTRAINT ck_bje_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED'))
);

CREATE TABLE data_validation_error (
    data_validation_error_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_job_execution_id   BIGINT NOT NULL REFERENCES batch_job_execution(batch_job_execution_id) ON DELETE RESTRICT,
    error_type               VARCHAR(50) NOT NULL,
    source_ref               VARCHAR(500),
    case_external_ref        VARCHAR(100),
    category_id              VARCHAR(100),
    error_detail             JSON NOT NULL DEFAULT '{}'::json,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE accident_review (
    review_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accident_id        BIGINT       NOT NULL REFERENCES accident(accident_id) ON DELETE CASCADE,
    status             VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    reviewed_job_id    BIGINT       REFERENCES analysis_job(job_id) ON DELETE SET NULL,
    snapshot_actual_repair_cost INTEGER,
    reviewer_member_id BIGINT       REFERENCES member(member_id) ON DELETE SET NULL,
    reject_reason      VARCHAR(500),
    queued_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    reviewed_at        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_ar_accident UNIQUE (accident_id),
    CONSTRAINT ck_ar_status   CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    CONSTRAINT ck_ar_done     CHECK ((status =  'PENDING') = (reviewed_at IS NULL)),
    CONSTRAINT ck_ar_reject   CHECK ((status =  'REJECTED') = (reject_reason IS NOT NULL)),
    CONSTRAINT ck_ar_cost     CHECK (snapshot_actual_repair_cost IS NULL
                                  OR snapshot_actual_repair_cost > 0)
);

CREATE INDEX ix_ar_queue ON accident_review (status, queued_at);
