-- ============================================================
-- 테스트용 스키마 (H2, PostgreSQL 호환 모드)
-- Docs/Erd/A307_ddl_final.sql 중 차량·사고와 견적 검증에 필요한 읽기/쓰기 테이블을 옮겼다.
-- 컬럼명 · NULL 여부 · CHECK 제약은 원본과 같게 유지한다 (Entity 매핑 검증 목적).
--
-- 원본과 다른 점 (H2 미지원)
--   · 부분 인덱스 WHERE 절 → 전체 인덱스로 대체
--   · BIGSERIAL → GENERATED BY DEFAULT AS IDENTITY
-- ============================================================

DROP TABLE IF EXISTS estimate_validation_question;
DROP TABLE IF EXISTS estimate_validation_report;
DROP TABLE IF EXISTS estimate_validation_item;
DROP TABLE IF EXISTS estimate_validation;
DROP TABLE IF EXISTS estimate_item;
DROP TABLE IF EXISTS estimate;
DROP TABLE IF EXISTS damaged_part;
DROP TABLE IF EXISTS analysis_job;
DROP TABLE IF EXISTS repair_cost_stat;
DROP TABLE IF EXISTS part_name_mapping;
DROP TABLE IF EXISTS part_code;
DROP TABLE IF EXISTS accident_image_asset;
DROP TABLE IF EXISTS accident_image;
DROP TABLE IF EXISTS accident;
DROP TABLE IF EXISTS vehicle;
DROP TABLE IF EXISTS vehicle_model;
DROP TABLE IF EXISTS terms_agreement;
DROP TABLE IF EXISTS member;

CREATE TABLE member (
    member_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider          VARCHAR(20)  NOT NULL,
    provider_user_id  VARCHAR(255) NOT NULL,
    nickname          VARCHAR(12)  NOT NULL,
    email             VARCHAR(255),
    profile_image_key VARCHAR(500),
    role              VARCHAR(20)  NOT NULL DEFAULT 'USER',
    status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    withdrawn_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_member_provider UNIQUE (provider, provider_user_id),
    CONSTRAINT ck_member_provider CHECK (provider IN ('KAKAO','GOOGLE')),
    CONSTRAINT ck_member_role     CHECK (role IN ('USER','ADMIN')),
    CONSTRAINT ck_member_status   CHECK (status IN ('ACTIVE','WITHDRAWN'))
);

CREATE TABLE terms_agreement (
    agreement_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    BIGINT      NOT NULL REFERENCES member(member_id) ON DELETE RESTRICT,
    terms_type   VARCHAR(20) NOT NULL,
    version      VARCHAR(20) NOT NULL,
    agreed_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_terms_type CHECK (terms_type IN ('SERVICE','PRIVACY'))
);

CREATE TABLE vehicle_model (
    model_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer VARCHAR(50)  NOT NULL,
    model_name   VARCHAR(100) NOT NULL,
    vehicle_type VARCHAR(20)  NOT NULL,
    car_class    VARCHAR(20)  NOT NULL,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_vm UNIQUE (manufacturer, model_name),
    CONSTRAINT ck_vm_type  CHECK (vehicle_type IN ('SEDAN','SUV','VAN','TRUCK')),
    CONSTRAINT ck_vm_class CHECK (car_class IN ('CityCar','Compact','Mid-size','Full-size'))
);

CREATE TABLE vehicle (
    vehicle_id BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT   NOT NULL REFERENCES member(member_id)       ON DELETE RESTRICT,
    model_id   BIGINT   NOT NULL REFERENCES vehicle_model(model_id) ON DELETE RESTRICT,
    model_year SMALLINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_v_year CHECK (model_year BETWEEN 1980 AND 2100)
);

CREATE INDEX ix_vehicle_member ON vehicle (member_id);

-- 삭제 테스트용. vehicle 을 ON DELETE RESTRICT 로 참조하는 유일한 테이블이다.
CREATE TABLE accident (
    accident_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id              BIGINT NOT NULL REFERENCES vehicle(vehicle_id) ON DELETE RESTRICT,
    vehicle_input_type      VARCHAR(10)  NOT NULL,
    snapshot_model_id       BIGINT       NOT NULL,
    snapshot_manufacturer   VARCHAR(50)  NOT NULL,
    snapshot_model_name     VARCHAR(100) NOT NULL,
    snapshot_vehicle_type   VARCHAR(20)  NOT NULL,
    snapshot_car_class      VARCHAR(20)  NOT NULL,
    snapshot_model_year     SMALLINT     NOT NULL,
    actual_repair_cost      INTEGER,
    actual_repair_completed_date DATE,
    repair_shop_name        VARCHAR(100),
    actual_cost_recorded_at TIMESTAMP WITH TIME ZONE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_ac_input_type CHECK (vehicle_input_type IN ('REGISTERED','DIRECT')),
    CONSTRAINT ck_ac_vehicle_type CHECK (snapshot_vehicle_type IN ('SEDAN','SUV','VAN','TRUCK')),
    CONSTRAINT ck_ac_car_class CHECK (snapshot_car_class IN ('CityCar','Compact','Mid-size','Full-size')),
    CONSTRAINT ck_ac_model_year CHECK (snapshot_model_year BETWEEN 1980 AND 2100),
    CONSTRAINT ck_ac_cost CHECK (actual_repair_cost IS NULL OR actual_repair_cost > 0)
);

-- 사고 이미지. 경로·크기 메타는 이 테이블이 아니라 accident_image_asset 에 있다.
-- 정본(A307_ddl_final.sql)과 컬럼·NULL 여부·CHECK·FK·인덱스를 항목별로 대조해 옮겼다.
CREATE TABLE accident_image (
    image_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accident_id       BIGINT       NOT NULL REFERENCES accident(accident_id) ON DELETE CASCADE,
    original_filename VARCHAR(255) NOT NULL,
    quality_status    VARCHAR(20)  NOT NULL DEFAULT 'PASS',
    quality_reason    VARCHAR(100),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_ai_quality CHECK (quality_status IN ('PASS','WARN'))
);

-- 원본·리사이즈·썸네일·블러를 행으로. variant 는 이미지당 1개(uk_aia).
-- OVERLAY 를 넣지 않는 것이 정본의 결정이다 — (job × image)마다 생겨 uk_aia 를 위반한다.
CREATE TABLE accident_image_asset (
    asset_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id   BIGINT       NOT NULL REFERENCES accident_image(image_id) ON DELETE CASCADE,
    variant    VARCHAR(20)  NOT NULL,
    s3_key     VARCHAR(500) NOT NULL,
    width      SMALLINT,
    height     SMALLINT,
    file_size  INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_aia      UNIQUE (image_id, variant),
    CONSTRAINT ck_aia_var  CHECK (variant IN ('ORIGINAL','RESIZED','THUMBNAIL','BLURRED')),
    CONSTRAINT ck_aia_size CHECK (file_size IS NULL OR file_size <= 20971520)
);

CREATE INDEX ix_img_accident ON accident_image (accident_id);

CREATE TABLE part_code (
    part_code     VARCHAR(50) PRIMARY KEY,
    name_ko       VARCHAR(50) NOT NULL,
    layout_zone   VARCHAR(20) NOT NULL,
    display_order SMALLINT NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_pc_zone CHECK (layout_zone IN ('FRONT','REAR','SIDE_L','SIDE_R','TOP','UNDER'))
);

CREATE TABLE part_name_mapping (
    raw_name  VARCHAR(200) PRIMARY KEY,
    part_code VARCHAR(50) NOT NULL REFERENCES part_code(part_code) ON DELETE RESTRICT
);

CREATE TABLE analysis_job (
    job_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accident_id    BIGINT NOT NULL REFERENCES accident(accident_id) ON DELETE CASCADE,
    status         VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    retry_count    SMALLINT NOT NULL DEFAULT 0,
    failure_reason VARCHAR(50),
    model_version  VARCHAR(50),
    started_at     TIMESTAMP WITH TIME ZONE,
    finished_at    TIMESTAMP WITH TIME ZONE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_aj_status CHECK (status IN ('QUEUED','PROCESSING','COMPLETED','FAILED')),
    CONSTRAINT ck_aj_retry CHECK (retry_count BETWEEN 0 AND 3)
);

CREATE TABLE damaged_part (
    damaged_part_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          BIGINT NOT NULL REFERENCES analysis_job(job_id) ON DELETE CASCADE,
    part_code       VARCHAR(50) NOT NULL REFERENCES part_code(part_code) ON DELETE RESTRICT,
    damage_type     VARCHAR(20) NOT NULL,
    repair_method   VARCHAR(20) NOT NULL,
    severity_score  NUMERIC(6,2),
    confidence      NUMERIC(5,4) NOT NULL,
    CONSTRAINT uk_dp UNIQUE (job_id, part_code),
    CONSTRAINT ck_dp_damage CHECK (damage_type IN ('Scratched','Separated','Crushed','Breakage')),
    CONSTRAINT ck_dp_method CHECK (repair_method IN ('coating','sheet_metal','exchange','repair'))
);

CREATE TABLE estimate (
    estimate_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id               BIGINT NOT NULL REFERENCES analysis_job(job_id) ON DELETE CASCADE,
    version              SMALLINT NOT NULL DEFAULT 1,
    is_estimable         BOOLEAN NOT NULL DEFAULT TRUE,
    non_estimable_reason VARCHAR(100),
    labor_rate           INTEGER,
    total_hq             NUMERIC(7,2),
    total_min            INTEGER,
    total_median         INTEGER,
    total_max            INTEGER,
    ref_case_total       INTEGER,
    confidence_grade     VARCHAR(10),
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_est UNIQUE (job_id, version)
);

CREATE TABLE estimate_item (
    estimate_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id       BIGINT NOT NULL REFERENCES estimate(estimate_id) ON DELETE CASCADE,
    damaged_part_id   BIGINT NOT NULL REFERENCES damaged_part(damaged_part_id) ON DELETE CASCADE,
    repair_method     VARCHAR(20) NOT NULL,
    standard_hq       NUMERIC(6,2),
    part_cost_median  INTEGER,
    labor_cost_median INTEGER,
    item_min          INTEGER NOT NULL,
    item_median       INTEGER NOT NULL,
    item_max          INTEGER NOT NULL,
    ref_case_count    INTEGER NOT NULL,
    ref_condition     JSON NOT NULL,
    is_low_confidence BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE repair_cost_stat (
    stat_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_class         VARCHAR(20) NOT NULL,
    part_code         VARCHAR(50) NOT NULL,
    damage_type       VARCHAR(20) NOT NULL,
    repair_method     VARCHAR(20) NOT NULL,
    source            VARCHAR(20) NOT NULL,
    case_count        INTEGER NOT NULL,
    hq_median         NUMERIC(6,2),
    cost_min          INTEGER NOT NULL,
    cost_p25          INTEGER NOT NULL,
    cost_median       INTEGER NOT NULL,
    cost_p75          INTEGER NOT NULL,
    cost_max          INTEGER NOT NULL,
    part_cost_median  INTEGER,
    labor_cost_median INTEGER,
    aggregated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_rcs UNIQUE (car_class, part_code, damage_type, repair_method, source)
);

CREATE TABLE estimate_validation (
    validation_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id        BIGINT NOT NULL REFERENCES member(member_id) ON DELETE RESTRICT,
    accident_id      BIGINT NOT NULL REFERENCES accident(accident_id) ON DELETE CASCADE,
    estimate_id      BIGINT REFERENCES estimate(estimate_id) ON DELETE SET NULL,
    s3_key_file      VARCHAR(500),
    file_type        VARCHAR(10) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    claimed_total    INTEGER,
    llm_model        VARCHAR(50),
    llm_grade        VARCHAR(20),
    -- PostgreSQL DDL 의 TEXT 와 짝을 맞춘다. CLOB 이면 엔티티(String)가 기대하는
    -- VARCHAR 와 어긋나 스키마 검증이 실패한다.
    llm_summary      VARCHAR,
    failure_reason   VARCHAR(200),
    review_item_count INTEGER NOT NULL DEFAULT 0,
    total_item_count INTEGER NOT NULL DEFAULT 0,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    completed_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_ev_status CHECK (status IN ('QUEUED','PROCESSING','COMPLETED','FAILED')),
    CONSTRAINT ck_ev_type CHECK (file_type IN ('IMAGE','PDF','MANUAL')),
    CONSTRAINT ck_ev_grade CHECK (llm_grade IS NULL OR llm_grade IN ('APPROPRIATE','CAUTION','NEEDS_REVIEW')),
    CONSTRAINT ck_ev_file CHECK ((file_type = 'MANUAL' AND s3_key_file IS NULL)
                              OR (file_type <> 'MANUAL' AND s3_key_file IS NOT NULL))
);

CREATE TABLE estimate_validation_item (
    validation_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    validation_id      BIGINT NOT NULL REFERENCES estimate_validation(validation_id) ON DELETE CASCADE,
    line_no            SMALLINT NOT NULL,
    raw_item_name      VARCHAR(200) NOT NULL,
    normalized_item_name VARCHAR(100),
    part_code          VARCHAR(50) REFERENCES part_code(part_code) ON DELETE SET NULL,
    work_type          VARCHAR(20),
    quantity           SMALLINT NOT NULL DEFAULT 1,
    part_cost          INTEGER,
    labor_cost         INTEGER,
    subtotal           INTEGER,
    llm_flag           VARCHAR(30),
    llm_reason         VARCHAR(300),
    reference_min      INTEGER,
    reference_median   INTEGER,
    reference_p75      INTEGER,
    reference_max      INTEGER,
    reference_case_count INTEGER,
    CONSTRAINT uk_evi UNIQUE (validation_id, line_no)
);

CREATE TABLE estimate_validation_report (
    validation_id  BIGINT PRIMARY KEY REFERENCES estimate_validation(validation_id) ON DELETE CASCADE,
    status         VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    s3_key_pdf     VARCHAR(500),
    failure_reason VARCHAR(200),
    retry_count    SMALLINT NOT NULL DEFAULT 0,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    completed_at   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_evr_status CHECK (status IN ('QUEUED','PROCESSING','COMPLETED','FAILED')),
    CONSTRAINT ck_evr_retry CHECK (retry_count BETWEEN 0 AND 3)
);

CREATE TABLE estimate_validation_question (
    question_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    validation_id      BIGINT NOT NULL REFERENCES estimate_validation(validation_id) ON DELETE CASCADE,
    validation_item_id BIGINT REFERENCES estimate_validation_item(validation_item_id) ON DELETE CASCADE,
    source_flag        VARCHAR(30) NOT NULL,
    display_order      SMALLINT NOT NULL,
    question_text      VARCHAR(500) NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_evq_item_flag UNIQUE (validation_item_id, source_flag),
    CONSTRAINT uk_evq_order UNIQUE (validation_id, display_order)
);

CREATE INDEX ix_ev_member ON estimate_validation(member_id, created_at DESC);
CREATE INDEX ix_ev_accident ON estimate_validation(accident_id, created_at DESC);
