package com.ssafy.a307.schema;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 테스트 스키마({@code schema-h2.sql})가 정본({@code Docs/Erd/A307_ddl_final.sql})과 어긋나지 않는지
 * 본다. <b>prompt24 5장의 D-B(새 의존성 없는 정적 대조)</b> 구현이다.
 *
 * <p><b>왜 필요한가.</b> {@code schema-h2.sql} 은 손으로 유지하는 별도 사본이고, 테스트의
 * {@code ddl-auto=validate} 는 정본이 아니라 <b>그 사본</b>을 검증한다. 사본이 낡으면
 * "테스트 전부 통과" 가 "운영에서 기동됨" 을 더 이상 뜻하지 않는다. 실제로 그 사고가 일어났다 —
 * {@code estimate_validation.llm_summary} 가 정본 {@code TEXT} · H2 {@code CLOB} 이었고 엔티티의
 * {@code @Lob} 이 H2 하고만 맞아, 365개 테스트가 전부 통과하는 채로 PostgreSQL 기동만
 * {@code SchemaManagementException} 으로 죽었다(answer24 F-1).
 *
 * <p><b>무엇을 보장하는가.</b> H2 에 존재하는 테이블에 한해 컬럼·타입·NULL 여부·DEFAULT·CHECK·
 * UNIQUE·FK 정의가 정본과 <b>글자 단위로</b> 같아야 한다. 다른 것이 허용되는 경우는
 * {@link #H2_SUBSTITUTIONS} 에 적힌 H2 미지원 치환뿐이고, 그 목록은 파일 머리말에도 같이 적혀
 * 있어야 한다({@link Header}). 치환을 늘리려면 두 곳을 함께 고쳐야 하므로 조용히 늘어나지 않는다.
 *
 * <p><b>무엇을 보장하지 않는가.</b> 정본에 있고 H2 에 없는 테이블은 실패시키지 않는다 — 아직
 * 엔티티도 소비자도 없는 도메인이라 옮길 이유가 없다. 대신 그 목록을 고정해 두어
 * <b>새 누락이 생기면 깨진다</b>({@link Coverage}). JPA ↔ H2 일치는 이 테스트가 보지 않는다.
 * {@code ddl-auto=validate} 가 컨텍스트 기동 시점에 검증하므로 매핑이 어긋나면
 * {@code @SpringBootTest} 가 통째로 뜨지 않는다 — 셋 중 둘을 여기서, 나머지 하나를 기동으로 본다.
 */
@DisplayName("스키마 정본 대조 (정본 DDL ↔ schema-h2.sql)")
class SchemaConformityTest {

    /**
     * 정본 표기를 H2 표기로 바꾸는 치환. <b>정본 쪽에만 단방향으로 적용한다</b> —
     * 양방향으로 두면 H2 가 정본보다 넓은 타입을 써도 통과해 버린다.
     *
     * <p>{@code description} 은 {@code schema-h2.sql} 머리말에 그대로 들어 있어야 한다.
     */
    private static final List<Substitution> H2_SUBSTITUTIONS = List.of(
            new Substitution("BIGSERIAL", "BIGINT GENERATED BY DEFAULT AS IDENTITY",
                    "BIGSERIAL → GENERATED BY DEFAULT AS IDENTITY"),
            new Substitution("TIMESTAMPTZ", "TIMESTAMP WITH TIME ZONE",
                    "TIMESTAMPTZ → TIMESTAMP WITH TIME ZONE"),
            new Substitution("JSONB", "JSON",
                    "JSONB → JSON"),
            // TEXT ↔ VARCHAR 는 타입군이 같다(둘 다 Types.VARCHAR 로 보고된다).
            // 이 치환이 성립하는 것이 @Lob 을 떼는 근거이기도 하다 — answer24 F-1.
            new Substitution("TEXT", "VARCHAR",
                    "TEXT → VARCHAR"));

    /**
     * 정본에 있지만 H2 로 옮기지 않은 테이블. <b>엔티티도 소비자도 없는 도메인</b>이라 당장 옮길
     * 이유가 없다. 이 목록을 고정해 두는 이유는 반대 방향이다 — 엔티티가 생겨 H2 로 옮기면
     * 여기서 지워야 하고, 새 테이블이 정본에 추가되면 이 테스트가 먼저 깨진다.
     */
    private static final Set<String> KNOWN_MISSING_TABLES = new TreeSet<>(Set.of(
            "EMBEDDING_MODEL_VERSION",
            "ESTIMATE_REPORT",
            "REPAIR_CASE",
            "REPAIR_CASE_IMAGE",
            "REPAIR_CASE_ITEM",
            "REPAIR_CASE_ROI_EMBEDDING",
            // ↓ S15P21A307-232(유사 사례 검색 코퍼스)가 정본에만 더한 셋. 파이프라인이 쓰고
            //   서비스 엔티티가 없어 H2 로 옮기지 않았다 — 여기 적힌 나머지와 성격이 같다.
            //   테이블이 잘못된 것이 아니라 이 목록이 뒤늦게 따라온 것이다(아래 Coverage 주석).
            "FEATURE_PIPELINE_VERSION",
            "REPAIR_CASE_DAMAGE_FEATURE",
            "REPAIR_CASE_IMAGE_PART_ANNOTATION",
            // ↓ S15P21A307-556(v2 DAMAGE corpus · YOLO 부품 후보)가 정본에만 더한 넷. 232 와 같은
            //   성격이다 — 파이프라인이 쓰고 서비스 엔티티가 없어 H2 로 옮길 이유가 없다.
            "REPAIR_CASE_DAMAGE_FEATURE_PART_CANDIDATE",
            "REPAIR_CASE_DAMAGE_FEATURE_PART_HINT",
            "REPAIR_CASE_DAMAGE_FEATURE_PART_MAPPING",
            "REPAIR_CASE_IMAGE_PART_INFERENCE"));

    @ParameterizedTest(name = "{0}")
    @MethodSource("sharedTables")
    @DisplayName("H2 에 있는 테이블은 정본과 정의가 같다")
    void sharedTableMatchesCanonical(String table) {
        List<String> canonical = canonical().get(table);
        List<String> h2 = h2().get(table);

        assertThat(h2)
                .as("%s 의 정의가 정본과 다르다. H2 를 정본보다 약하게 만들지 말 것", table)
                .containsExactlyElementsOf(canonical);
    }

    @Test
    @DisplayName("정본에 없는 테이블을 H2 가 임의로 만들지 않는다")
    void h2HasNoInventedTables() {
        Set<String> invented = new LinkedHashSet<>(h2().keySet());
        invented.removeAll(canonical().keySet());

        assertThat(invented).isEmpty();
    }

    @Test
    @DisplayName("정본에 없는 인덱스를 H2 가 임의로 만들지 않는다")
    void h2HasNoInventedIndexes() {
        Set<String> invented = new LinkedHashSet<>(indexNames(rawH2()));
        invented.removeAll(indexNames(rawCanonical()));

        assertThat(invented).isEmpty();
    }

    @Nested
    @DisplayName("F-1 회귀 방어 — llm_summary")
    class LobRegression {

        @Test
        @DisplayName("H2 스키마에 LOB 계열 컬럼이 하나도 없다")
        void noLobColumns() {
            // 정본에는 CLOB·BLOB·BYTEA 가 한 번도 나오지 않는다. H2 에 생겼다면 그것이 divergence 다.
            assertThat(stripComments(rawCanonical()))
                    .doesNotContainIgnoringCase("CLOB")
                    .doesNotContainIgnoringCase("BLOB")
                    .doesNotContainIgnoringCase("BYTEA");
            assertThat(stripComments(rawH2()))
                    .as("llm_summary 를 CLOB 으로 되돌리면 H2 만 통과하고 PostgreSQL 기동이 죽는다")
                    .doesNotContainIgnoringCase("CLOB")
                    .doesNotContainIgnoringCase("BLOB");
        }

        @Test
        @DisplayName("llm_summary 는 정본 TEXT · H2 VARCHAR 로 타입군이 같다")
        void llmSummaryIsCharacterType() {
            assertThat(definition(canonicalWithoutSubstitution(), "ESTIMATE_VALIDATION", "LLM_SUMMARY"))
                    .isEqualTo("TEXT");
            assertThat(definition(h2(), "ESTIMATE_VALIDATION", "LLM_SUMMARY"))
                    .isEqualTo("VARCHAR");
        }
    }

    @Nested
    @DisplayName("F-2 회귀 방어 — CHECK 제약")
    class CheckConstraints {

        @Test
        @DisplayName("H2 에 있는 테이블의 CHECK 제약이 하나도 빠지지 않았다")
        void noCheckIsDropped() {
            Map<String, Set<String>> missing = new LinkedHashMap<>();
            for (String table : sharedTableNames()) {
                Set<String> canonicalChecks = constraintNames(canonical().get(table), "CHECK");
                Set<String> h2Checks = constraintNames(h2().get(table), "CHECK");
                canonicalChecks.removeAll(h2Checks);
                if (!canonicalChecks.isEmpty()) missing.put(table, canonicalChecks);
            }

            assertThat(missing)
                    .as("테스트를 통과시키려고 CHECK 를 빼지 말 것 — 운영에서만 거부되는 경로가 생긴다")
                    .isEmpty();
        }

        @Test
        @DisplayName("H2 에 있는 테이블의 UNIQUE 제약도 빠지지 않았다")
        void noUniqueIsDropped() {
            Map<String, Set<String>> missing = new LinkedHashMap<>();
            for (String table : sharedTableNames()) {
                Set<String> canonicalUniques = constraintNames(canonical().get(table), "UNIQUE");
                Set<String> h2Uniques = constraintNames(h2().get(table), "UNIQUE");
                canonicalUniques.removeAll(h2Uniques);
                if (!canonicalUniques.isEmpty()) missing.put(table, canonicalUniques);
            }

            assertThat(missing).isEmpty();
        }
    }

    @Nested
    @DisplayName("커버리지")
    class Coverage {

        @Test
        @DisplayName("정본 47테이블 중 34개가 H2 에 있고 누락 13개의 목록이 고정되어 있다")
        void missingTablesAreKnown() {
            Set<String> missing = new TreeSet<>(canonical().keySet());
            missing.removeAll(h2().keySet());

            // 관리자 기능이 정본에 3개(repair_code · repair_method_rule · estimate_validation_rule)를
            // 더했고, 그 셋과 audit_log 까지 4개를 H2 로 옮겼다. audit_log 는 엔티티가 생겨
            // 더 이상 누락일 수 없다 — 없으면 컨텍스트가 뜨지 않는다.
            // prompt58 이 analysis_stage 에 엔티티를 붙이며 한 개를 더 옮겼다(22 → 23).
            //
            // S15P21A307-232(유사 사례 검색 코퍼스)가 정본에만 3개를 더하면서 이 수치를 함께
            // 고치지 않아 이 테스트가 깨져 있었다(32 기대 / 35 실제). 32 → 35, 누락 9 → 12 로
            // 실제에 맞춘다. H2 는 늘지 않았다 — 셋 다 파이프라인 전용이라 옮길 이유가 없다.
            //
            // S15P21A307-288 이 estimate_notice 를 양쪽에 더했다(35/23 → 36/24). 누락은 12 그대로다.
            // S15P21A307-157 이 analysis_image_result 에 엔티티를 붙이며 H2 로 옮겼다(24 → 25,
            // 누락 12 → 11). 엔티티가 생기면 옮겨야 한다 — 안 옮기면 컨텍스트부터 뜨지 않는다.
            //
            // S15P21A307-509 가 정비 체크리스트 3종을 양쪽에 더했다(36/25 → 39/28). 누락은 11 그대로다.
            // 아직 엔티티는 없지만 -460·-461·-463·-483 이 곧 붙이므로 처음부터 H2 에 뒀다 —
            // 나중에 옮기면 그 사이에 KNOWN_MISSING_TABLES 를 거쳐야 하고, 거기 들어간 테이블은
            // 엔티티가 생기는 순간 기동 실패로만 드러난다.
            //
            // S15P21A307-510 이 정비소 확인 질문 2종(repair_question · repair_question_item)을
            // 양쪽에 더했다(39/28 → 41/30). 누락은 11 그대로다. -509 와 같은 이유로 처음부터
            // H2 에 뒀다 — -477 이 곧 엔티티를 붙인다.
            //
            // S15P21A307-513 이 사고 데이터 검수(accident_review)를 양쪽에 더했다(41/30 → 42/31).
            // 누락은 11 그대로다. 역시 엔티티보다 스키마가 먼저다 — -350 이 곧 붙인다.
            //
            // S15P21A307-537 이 견적 리포트 요약(estimate_narrative)을 양쪽에 더했다(42/33 → 43/34).
            // 누락은 그대로다. 엔티티가 같은 커밋에 들어왔으므로 H2 에 없으면 컨텍스트부터 뜨지 않는다.
            //
            // S15P21A307-556 이 파이프라인 테이블 4개를 정본에만 더했다(43/34 → 47/34, 누락 9 → 13).
            // 232 때처럼 수치를 함께 고치지 않아 깨졌고, S15P21A307-560 에서 맞췄다. H2 는 그대로다.
            //
            // 새 테이블이 한쪽에만 들어가면 여기서 깨진다. 그것이 이 테스트의 목적이다.
            assertThat(canonical()).hasSize(47);
            assertThat(h2()).hasSize(34);
            assertThat(missing)
                    .as("정본에 테이블이 늘었거나 H2 로 옮겼다면 KNOWN_MISSING_TABLES 와 머리말을 함께 고칠 것")
                    .isEqualTo(KNOWN_MISSING_TABLES);
        }

        @Test
        @DisplayName("@Entity 가 붙은 테이블은 전부 H2 에 있다 — 그래서 validate 가 통과한다")
        void everyMappedTableExists() {
            // 누락 11개 중 어느 것에도 엔티티가 없다는 사실을 고정한다.
            // 엔티티가 생기는 순간 H2 로 옮겨야 하고, 안 옮기면 그 테스트가 컨텍스트부터 뜨지 않는다.
            // 정비 체크리스트 3종은 엔티티보다 스키마가 먼저 들어왔다(S15P21A307-509). 이미 H2 에
            // 있으므로 누락일 수 없고, 누락 목록에 넣어 이 테스트를 통과시키려 해서도 안 된다.
            // 정비소 확인 질문 2종(S15P21A307-510)도 같다 — -477 이 엔티티를 붙인다.
            // 사고 데이터 검수(S15P21A307-513)도 같다 — -350 이 엔티티를 붙인다.
            assertThat(KNOWN_MISSING_TABLES)
                    .doesNotContain("ACCIDENT", "ACCIDENT_IMAGE", "ACCIDENT_IMAGE_ASSET",
                            "VEHICLE", "VEHICLE_MODEL", "MEMBER", "TERMS_AGREEMENT",
                            "ESTIMATE", "ESTIMATE_ITEM", "ESTIMATE_VALIDATION",
                            "ESTIMATE_VALIDATION_ITEM", "ESTIMATE_VALIDATION_REPORT",
                            "ESTIMATE_VALIDATION_QUESTION", "REPAIR_COST_STAT",
                            "PART_CODE", "PART_NAME_MAPPING",
                            "AUDIT_LOG", "REPAIR_CODE", "REPAIR_METHOD_RULE",
                            "ESTIMATE_VALIDATION_RULE", "ANALYSIS_STAGE",
                            "ESTIMATE_NOTICE", "ANALYSIS_IMAGE_RESULT",
                            "REPAIR_CHECKLIST", "REPAIR_CHECKLIST_ITEM",
                            "REPAIR_CHECKLIST_COMMON_ITEM",
                            "REPAIR_QUESTION", "REPAIR_QUESTION_ITEM",
                            "ACCIDENT_REVIEW",
                            "BATCH_JOB_EXECUTION", "DATA_VALIDATION_ERROR");
        }
    }

    @Nested
    @DisplayName("F-4 회귀 방어 — 머리말")
    class Header {

        @Test
        @DisplayName("실제로 적용한 H2 치환이 전부 머리말에 적혀 있다")
        void everySubstitutionIsDocumented() {
            String header = header(rawH2());

            assertThat(H2_SUBSTITUTIONS)
                    .allSatisfy(substitution -> assertThat(header)
                            .as("치환 '%s' 이 머리말에 없다. 미문서화 치환을 늘리지 말 것",
                                    substitution.description())
                            .contains(substitution.description()));
        }

        @Test
        @DisplayName("머리말이 정본 위치와 테스트 전용이라는 사실을 밝힌다")
        void headerNamesTheCanonicalSource() {
            String header = header(rawH2());

            assertThat(header).contains("Docs/Erd/A307_ddl_final.sql");
            assertThat(header).contains("테스트 전용");
        }
    }

    // ---------------------------------------------------------------- 파싱

    private record Substitution(String canonicalToken, String h2Token, String description) {

        String apply(String sql) {
            return sql.replaceAll("\\b" + Pattern.quote(canonicalToken) + "\\b",
                    Matcher.quoteReplacement(h2Token));
        }
    }

    static Stream<String> sharedTables() {
        return sharedTableNames().stream();
    }

    private static List<String> sharedTableNames() {
        List<String> shared = new ArrayList<>(canonical().keySet());
        shared.retainAll(h2().keySet());
        return shared;
    }

    /** 정본을 H2 표기로 치환한 뒤 파싱한 결과. */
    private static Map<String, List<String>> canonical() {
        String sql = normalize(rawCanonical());
        for (Substitution substitution : H2_SUBSTITUTIONS) {
            sql = substitution.apply(sql);
        }
        return parse(sql);
    }

    /** 치환 없이 파싱한 정본. 치환 자체가 맞는지 볼 때만 쓴다. */
    private static Map<String, List<String>> canonicalWithoutSubstitution() {
        return parse(normalize(rawCanonical()));
    }

    private static Map<String, List<String>> h2() {
        return parse(normalize(rawH2()));
    }

    /**
     * {@code CREATE TABLE ... ( ... );} 을 테이블별 정의 목록으로 나눈다.
     * 괄호 깊이를 세므로 {@code NUMERIC(7,2)} 나 CHECK 안의 쉼표에 걸리지 않는다.
     */
    private static Map<String, List<String>> parse(String sql) {
        Map<String, List<String>> tables = new LinkedHashMap<>();
        Matcher matcher = Pattern.compile("CREATE TABLE (\\w+) \\(").matcher(sql);
        while (matcher.find()) {
            int start = matcher.end();
            int end = closingParen(sql, start);
            tables.put(matcher.group(1), split(sql.substring(start, end)));
        }
        return tables;
    }

    private static int closingParen(String sql, int start) {
        int depth = 1;
        for (int i = start; i < sql.length(); i++) {
            char c = sql.charAt(i);
            if (c == '(') depth++;
            if (c == ')' && --depth == 0) return i;
        }
        throw new IllegalStateException("CREATE TABLE 의 괄호가 닫히지 않았다");
    }

    private static List<String> split(String body) {
        List<String> definitions = new ArrayList<>();
        StringBuilder current = new StringBuilder();
        int depth = 0;
        for (char c : body.toCharArray()) {
            if (c == '(') depth++;
            if (c == ')') depth--;
            if (c == ',' && depth == 0) {
                addTo(definitions, current);
                continue;
            }
            current.append(c);
        }
        addTo(definitions, current);
        return definitions;
    }

    private static void addTo(List<String> definitions, StringBuilder current) {
        String value = current.toString().strip();
        if (!value.isEmpty()) definitions.add(value);
        current.setLength(0);
    }

    /** 한 컬럼의 타입·제약 부분(컬럼명 제외). */
    private static String definition(Map<String, List<String>> tables, String table, String column) {
        return tables.getOrDefault(table, List.of()).stream()
                .filter(definition -> definition.equals(column) || definition.startsWith(column + " "))
                .map(definition -> definition.substring(column.length()).strip())
                .findFirst()
                .orElseThrow(() -> new AssertionError(table + "." + column + " 을 찾지 못했다"));
    }

    private static Set<String> constraintNames(List<String> definitions, String keyword) {
        Set<String> names = new TreeSet<>();
        for (String definition : definitions) {
            Matcher matcher = Pattern.compile("^CONSTRAINT (\\w+) " + keyword + "\\b").matcher(definition);
            if (matcher.find()) names.add(matcher.group(1));
        }
        return names;
    }

    private static Set<String> indexNames(String sql) {
        Set<String> names = new TreeSet<>();
        Matcher matcher = Pattern.compile("CREATE INDEX (\\w+)").matcher(normalize(sql));
        while (matcher.find()) names.add(matcher.group(1));
        return names;
    }

    /** 주석 제거 · 공백 한 칸 정리 · 대문자화. 표기 치환은 여기서 하지 않는다. */
    private static String normalize(String sql) {
        return stripComments(sql)
                .replaceAll("\\s+", " ")
                .toUpperCase(Locale.ROOT)
                .replaceAll("\\s*\\(\\s*", " (")
                .replaceAll("\\s*\\)\\s*", ") ")
                .replaceAll("\\s+", " ")
                .replaceAll("\\s*,\\s*", ", ");
    }

    private static String stripComments(String sql) {
        return sql.replaceAll("--[^\\n]*", " ");
    }

    /** 첫 {@code CREATE}/{@code DROP} 이전까지가 머리말이다. */
    private static String header(String sql) {
        Matcher matcher = Pattern.compile("(?m)^\\s*(CREATE|DROP)\\b").matcher(sql);
        return matcher.find() ? sql.substring(0, matcher.start()) : sql;
    }

    private static String rawCanonical() {
        return read(repoFile("Docs/Erd/A307_ddl_final.sql"));
    }

    private static String rawH2() {
        Path fromModule = Path.of("src/test/resources/schema-h2.sql");
        return read(Files.exists(fromModule) ? fromModule : Path.of("backend").resolve(fromModule));
    }

    private static String read(Path path) {
        try {
            return Files.readString(path, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("스키마 파일을 읽지 못했다: " + path, e);
        }
    }

    /** 테스트 작업 디렉터리가 {@code backend} 일 때와 저장소 루트일 때를 모두 지원한다. */
    private static Path repoFile(String relativePath) {
        Path fromModule = Path.of("..").resolve(relativePath);
        return Files.exists(fromModule) ? fromModule : Path.of(relativePath);
    }
}
